name: Go Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0 # Fetch all history for all tags

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.23' # Use the Go version you need

    - name: Set Goproxy
      run: |
        echo "export GOPROXY=https://goproxy.cn,direct" >> $GITHUB_ENV

    - name: Download Go Modules
      run: go mod download

    - name: Build Go Project
      run: go build -o main .
